site_name: Mars-Jetson-Documentation

site_url: https://MARS-UVA.github.io/mars-jetson/

theme:
  name: material

nav:
  - Home: index.md
  - Setup: setup.md
  - DigDump: digdump.md
  - Teleop: teleop.md
  - Messages: messages.md